BURGERBASE:FUNC_MENU_AddTitle("Counter-Strike - Equipment Settings",false)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_flashbang_dur",false,"Maximum Flashbang Blind Duration",10,1)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_smoke_dur",false,"Smokegrenade smoke Duration",30,0)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_he_damage",false,"HE Grenade Maximum Explosion Damage",300,0)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_he_radius",false,"HE Grenade Radius",1000,0)

BURGERBASE:FUNC_MENU_AddTitle("Counter-Strike - C4 Settings",false)
BURGERBASE:FUNC_MENU_AddConVarCheckbox("sv_burgerbase_c4_nonadmin",false,"Enable non-admin pickup.")
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_c4_time_explosion",false,"Explosion Delay",300,0)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_c4_time_defuse",false,"Defuse Time",60,0)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_c4_timelimit",false,"C4 Replant Delay",600,0)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_c4_damage",false,"Maximum Explosion Damage",1000,0)
BURGERBASE:FUNC_MENU_AddConVarSlider("sv_burgerbase_c4_radius",false,"Explosion Radius",5000,0)
BURGERBASE:FUNC_MENU_AddConVarCheckbox("sv_burgerbase_c4_notifyplayers",false,"Plant and Explosion Notifications")